### ISSUE TITLE
Call to a member function getGroups() on null

### ISSUE THREAD

**Issue by mmcev106** [lsgs/redcap-dag-switcher#2]
This seems like a minor issue.  We've only seen this error twice:

```
The 'hook_every_page_top' hook did not complete for the 'dag_switcher' module because of the following error:

Error Message: Call to a member function getGroups() on null
File: /app001/www/redcap/redcap_v8.6.2/Classes/REDCap.php
Line: 886


URL: https://redcap.vanderbilt.edu/redcap_v8.6.2/index.php?route=SendItController:upload&loc=#&id=#######
Server: redcap.vanderbilt.edu (ori27lp)
Hook Run Time: 0 seconds
```

```
The 'hook_every_page_top' hook did not complete for the 'dag_switcher' module because of the following error:

Error Message: Call to a member function getGroups() on null
File: /app001/www/redcap/redcap_v8.7.3/Classes/REDCap.php
Line: 886


URL: https://redcap.vanderbilt.edu/redcap_v8.7.3/index.php?route=SendItController:upload&loc=#&id=#######
Server: redcap.vanderbilt.edu (ori27lp)
Hook Run Time: 0 seconds
```

I can't really justify the time to troubleshoot it, but I wanted to post it in case it would be helpful.  I wonder if a null check could be added to avoid this.

**Comment by lsgs** [comment]
Thanks very much @mmcev106 . I will look into it myself...

**Comment by lsgs** [comment]
I've released a fix for this @mmcev106 . v1.1.1. The exception was being thrown when a non-superuser uses SendIt to send project files e.g. export results. It did not prevent SendIt from working.

It happened because although the pid was passed to the hook function (redcap_every_page_top) there is no project context when using that particular Route (i.e. global $Proj is not set). The fix is just to return from the hook under that circumstance.

**Comment by mmcev106** [comment]
Thanks very much @lsgs!
