### ISSUE TITLE
Records in multiple DAGs?

### ISSUE THREAD

**Issue by vortexing** [lsgs/redcap-dag-switcher#3]
I'm considering your module b/c it sounds like what I need, with the possible exception of the need for some records to be in multiple DAGs as well as users being able to be in multiple DAGs like you have here.  Is that something that makes sense to add to this?

**Comment by lsgs** [comment]
Hello @vortexing , and apologies for the delay in replying. This module enables project users with DAG config permission to associate project users with more than one DAG. Those users may then switch between the DAGs they are associated with as and when they need to, but it keeps within REDCap's user/DAG model of a user being in only a single DAG at any one time (or not assigned).

The DAG assignment of project records already operates this way in that records are in at most one DAG at any time, but may be switched between DAGs as needed, although it is true that this can only be done by a user not assigned to a DAG. 

So what is the additional functionality you are looking for? What would it mean for a record to be "in multiple DAGs"?

**Comment by vortexing** [comment]
I have a situation where I'm using REDCap to hold metadata in each record that corresponds to a specific genomic data set (outside of REDCap).  That genomic data set could be part of Project A initially and thus accessible by study members of Project A. But then in the future may become ALSO part of Project B, and be accessible to study members of Project B.  So with your module it looks like I can have some number of the study members of Project A also be part of Project B by switching their DAG's, which is great.  However, there might be records that are shared between Project A and Project B such that they would need to show up in both DAGs.  Right now I would have to duplicate a record that becomes part of a new project, and I can't do that because then the REDcap record ID would not be unique.  

Is that more clear?  I'm not sure it is.  

ETA:  Essentially I'd love if there was a way to combine your user DAG switching module, with essentially a concatenated list of DAGs in the DAG field in each record.

**Comment by lsgs** [comment]
That does make sense. I don't think it's "DAG switching" for records that you need though - your requirement seems more about controlling access to records based on some property of the record. Switching a record from DAG A to DAG B because a B user wants to see it would then stop an A user seeing it until it got switched back. That's not going to work.

A question. Do the study members actually need to _enter_ data? If not, then you could meet your requirement by recording the studies a record is associated with in a checkbox field and then set up a series of reports with appropriate filters and user-access restrictions (e.g. roles for StudyA, StudyB, StudyAB), then disable data entry form access for those users.

If the study members do need to enter data then copying the record to another DAG is probably the best solution. If you can write hooks or modules then you would be able to streamline the process and ensure updates got copied across when required.

**Comment by vortexing** [comment]
I currently DO have the study-memberships as a series of radio buttons for simplicity which is how I manage this issue now, but don't have reports set up for users to see but likely will dive into these issues soon to address the problem.  

To clarify, the records don't need to DAG switch.  They would be part of study A for a long while (visible by users when they are in DAG A mode), then maybe become part of study A and B in the future for another long while (thus visible to users when they are in DAG A or DAG B mode).  It's just that the users need to do DAG switching (which is why I was looking at your module).  

If I could have the users DAG-switch like you have set up, and THEN also have the records be able to be in multiple DAGs simultaneously (no need to switch back and forth), then I wouldn't have to have checkboxes galore, nor limit read/write access to only reports, etc.  It was just a thought.

**Comment by lsgs** [comment]
Fair enough. I guess my point is that this module facilitates _switching_ of DAGs, which is not what you want for your records. It would be feasible to build a module that will do what you need, but I don't think this module is necessarily a good template for that.

**Comment by clinical-user** [comment]
Hi @vortexing did you find a solution to this?

**Comment by clinical-user** [comment]
> Hi @vortexing did you find a solution to this?

I am currently having the same issue with shared records as well and I'd love to know if you made any progress on this since then or know of any new API solutions
